### ISSUE TITLE
no-drag not working. drop fails to find $asSortableItemController

### ISSUE THREAD

**Issue by nitro52** [a5hik/ng-sortable#139]
I have a sortable list that looks like this

```html
    <ul ng-show="model.Items" data-as-sortable="sortableOptions" ng-model="model.Items">
        <li ng-repeat="item in model.Items" data-as-sortable-item>
            <div data-no-drag data-as-sortable-item-handle>
                <cover item="item"></cover>
            </div>
        </li>
    </ul>
```
with a cover directive that looks something like this

```html
<!-- cover directive template -->
<div class="cover">
    <a href="{{item.ItemUrl}}">
        <img ng-src="{{item.ImageUrl}}"/>
    </a>
</div>
```
The issue is that dropping does not work for me. I did some debugging and found this code to be the issue in the dragMove event

```javascript
              var asSortableItemController = targetElement.data().$asSortableItemController || targetElement.parent().data().$asSortableItemController;
              if (asSortableItemController) {
                targetScope = asSortableItemController.scope;
              }

              if (!targetScope || !targetScope.type) {
                return;
              }
```

The target element in my case is the img element. This means asSortableItemController is never found because it only looks at itself or its direct parent. I assume no-drag is meant to prevent the targetElement from going any lower than the data-as-sortable-item-handle which is a div wrapper that i setup to make the covers draggable. But this seems to do nothing. The only visible part is the img though.

i've had to do a very messy hack to find the right parent. But this is fragile and will break if the structure of the html changes a bit.

I had to add an extra check like 
```javascript
 var asSortableItemController = targetElement.data().$asSortableItemController || targetElement.parent().data().$asSortableItemController || targetElement.parent().parent().parent().parent().data().$asSortableItemController
```

Is there no way to find the closest ancestor with the data-as-sortable attribute without using jquery?

**Comment by a5hik** [comment]
Hi the reported code clock with issue is recently added to fix no-debug problem for #94, I had reverted those changes now. and It should be working fine now.

and the idea of this library is to not dependent on any JQuery.

**Comment by nitro52** [comment]
ok thanks i'll check it out later. 

> "and the idea of this library is to not dependent on any JQuery."

thats what i mean. without using jquery is there still a failsafe way to navigate up the tree util you find the parent/ancestor that matches the angular directive? Or do you literally have to create a loop until you find the controller or the parent() returns undefined

**Comment by a5hik** [comment]
with the fix., it should be working fine.. If you still see any issue, please report.

**Comment by nitro52** [comment]
no-drag still does not seem to be working, I've pulled the latest change that and now the drop isn't working. Debugging it looks like the previous var asSortableItemController was changed to

              targetScope = targetElement.scope();

              if (!targetScope || !targetScope.type) {
                return;
              }

But in my case the targetScope.type is undefined. targetElement is the Image and not the parent div that contains the no-drag option. Any ideas?

**Comment by nitro52** [comment]
I think it might be because targetElement dosn't seem to be accounting for the no-drag element

targetElement = angular.element($document[0].elementFromPoint(targetX, targetY));
